#pragma once

enum {
	ARM_AND, ARM_EOR, ARM_SUB, ARM_RSB,
	ARM_ADD, ARM_ADC, ARM_SBC, ARM_RSC,
	ARM_TST, ARM_TEQ, ARM_CMP, ARM_CMN,
	ARM_ORR, ARM_MOV, ARM_BIC, ARM_MVN,
//
	ARM_ASR, ARM_LSL, ARM_LSR, ARM_ROR,
//
	ARM_MUL,
};
